puts "What SIZE sundae did you get?"
size = "small"
puts "I got a " + size + " sundae, and it was delicious."
puts "WHO screamed the loudest on a ride?"
who = "Allan"
puts who + " screamed the loudest"
puts "What COLOR of cotton candy was the most delicious?"
color = "Pink"
puts color + " cotton candy was the most delicious."
puts "HOW COLD was the water in the wave pool?"
how_cold = "lukewarm"
puts "The water in the wave pool is " + how_cold + "."
puts "Were your favorite rides CRAZY OR CALM?"
crazy = "Big dropper"
calm = "Teacup"
puts "My favorite rides are " + crazy + " and " + calm + "."
